### ISSUE TITLE
gosec medium severity: G114 (CWE-676): Use of net/http serve function that has no support for setting timeouts

### ISSUE THREAD

**Issue by aaryanyadav-ops** [lnproxy/lnproxy-relay#17]
> [lnproxy/lnproxy.go:659]
    658: 
    659: 	log.Fatalln(http.ListenAndServe("localhost:"+*httpPort, nil))
    660: }

**Comment by lnproxy** [comment]
I'm not going to add a dependency for this.  Sorry.
